apiVersion: apps/v1
kind: Deployment
metadata:
  name: userpostgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userPostgresql
  template:
    metadata:
      labels:
        app: userPostgresql
    spec:
      containers:
        - name: userpostgresql-container
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
          ports:
            - containerPort: 5432
