apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsvc-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productsvc
  template:
    metadata:
      labels:
        app: productsvc
    spec:
      containers:
      - name: usercontainer
        image: vanshk7/productsvc
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: product-postgresql-service
        - name: DB_PORT
          value: '5432'